spring:
  datasource:
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/cachenotdelete;AUTO_SERVER=TRUE;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;
    initialization-mode: embedded
    hikari:
      auto-commit: true
  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2
      enabled: false
  main:
    banner-mode: off
server:
  port: 35007
logging:
  level:
    root: error